# Generated by Django 4.1.4 on 2022-12-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=50)),
                ('Size', models.CharField(max_length=5)),
                ('Harga', models.CharField(max_length=30)),
                ('Ongkir', models.CharField(max_length=30)),
                ('M_pembayaran', models.CharField(max_length=50)),
            ],
        ),
    ]
