# Generated by Django 4.1.4 on 2022-12-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tampilan', models.CharField(max_length=50)),
                ('Warna', models.CharField(max_length=50)),
            ],
        ),
    ]
